name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install  # package.json'ı doğru dizinde bulacak şekilde çalıştırılır.

    - name: Build the project
      run: npm run build

    - name: Deploy to Render
      run: |
        # Render deploy komutları buraya gelecek
