name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodları GitHub'dan çekme
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Node.js kurulumunu yapma
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # 3. Bağımlılıkları yükleme
    - name: Install dependencies
      run: npm install
      working-directory: ./server  # GitHub Actions ortamında server dizini

    # 5. Render'a deploy
    - name: Deploy to Render
      run: |
        echo "Deploying to Render..."
        # Render'a yükleme komutlarını buraya ekleyin
        # Örneğin SSH komutları veya Render CLI komutları
