name: Deploy to Render

on:
  push:
    branches:
      - main   # Ana branch'ınız
  pull_request:
    branches:
      - main   # Ana branch'ınız

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Kullanmak istediğiniz Node.js sürümü

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test

    - name: Build the project
      run: |
        npm run build  # Eğer derleme veya önceden oluşturulması gereken dosyalar varsa

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Render API anahtarınızı GitHub Secrets'e ekleyin
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}  # Render service ID'nizi GitHub Secrets'e ekleyin
      run: |
        curl -X POST \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"service_id": "$RENDER_SERVICE_ID", "reason": "Deploy from GitHub"}' \
        https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploy
